# Banned Books BookNLP Analysis

**Summary:**
This notebook applies BookNLP to analyze banned books, extracting features and comparing literary elements across texts. It is focused on character, event, and stylistic analysis for banned literature.

# Banned Books BookNLP Analysis
This notebook analyzes banned books using BookNLP, focusing on extracting literary features, character and event data, and comparing results across the banned books corpus.
- **Dataset:** Banned books corpus (see Data/ for sources)
- **Methods:** BookNLP pipeline, text preprocessing, feature extraction, comparative analysis
- **Goal:** Explore literary patterns and metadata in banned books, and compare with other literary corpora.

# BookNLP of Banned Books

BookNLP sample data generated from our corpus of Banned Books are available on this Github repository: https://github.com/representationlab/booknlp_sample

A limited set of completely open data is available here: https://github.com/representationlab/booknlp_open

The following code pulls the BookNLP data for a specific book and allows you to explore it. You can change which book you want to view by visiting that books output files and linking the 'raw' version from Github in the 'wget' commands in the "Get Data" section.

# Installations

To use a GPU in Google Colab, change the following:

`Runtime > Change runtime type > Hardware accelerator > GPU`

To execute this notebook, sign in to Google and then run all cells

`Runtime > Run all`

In [ ]:
%pip install booknlp

In [ ]:
%%capture
import pandas as pd
!pip install booknlp
!python -m spacy download en_core_web_sm
from booknlp.booknlp import BookNLP

In [ ]:
model_params={
		"pipeline":"entity,quote,supersense,event,coref",
		"model":"big",
	}

booknlp=BookNLP("en", model_params)

{'pipeline': 'entity,quote,supersense,event,coref', 'model': 'big'}
--- startup: 17.758 seconds ---

# Import BookNLP Output Files

In [ ]:
import json
from collections import Counter

In [ ]:
def proc(filename):
    with open(filename) as file:
        data=json.load(file)
    return data

In [ ]:
%%capture
!wget https://raw.githubusercontent.com/representationlab/booknlp_sample/main/10%20Things%20I%20Can%20See%20From%20Here%20-%20Carrie%20Mac.txt.entities
!wget https://raw.githubusercontent.com/representationlab/booknlp_sample/main/10%20Things%20I%20Can%20See%20From%20Here%20-%20Carrie%20Mac.txt.quotes
!wget https://raw.githubusercontent.com/representationlab/booknlp_sample/main/10%20Things%20I%20Can%20See%20From%20Here%20-%20Carrie%20Mac.txt.book

In [ ]:
data=proc("/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.book")

# Explore Character Data

In [ ]:
import json

with open ("/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.book", "r") as f:
    book_data = json.load(f)
book_data.keys()

dict_keys(['characters'])

In [ ]:
len(book_data["characters"])

549

In [ ]:
book_data["characters"][0].keys()

dict_keys(['agent', 'patient', 'mod', 'poss', 'id', 'g', 'count', 'mentions'])

In [ ]:
book_data["characters"][0]["agent"][:1]
book_data["characters"][0]["patient"][:1]
book_data["characters"][0]["mod"][:1]
book_data["characters"][0]["poss"][:1]
book_data["characters"][0]["id"]
book_data["characters"][0]["g"]
book_data["characters"][0]["count"]
book_data["characters"][0]["mentions"].keys()

dict_keys(['proper', 'common', 'pronoun'])

In [ ]:
book_data["characters"][0]["mod"][:50]

[{'w': 'sick', 'i': 1466},
 {'w': 'person', 'i': 2540},
 {'w': 'late', 'i': 5766},
 {'w': 'surprised', 'i': 10045},
 {'w': 'sure', 'i': 10463},
 {'w': 'close', 'i': 11405},
 {'w': 'upset', 'i': 11451},
 {'w': 'little', 'i': 14951},
 {'w': 'person', 'i': 15660},
 {'w': 'person', 'i': 15681},
 {'w': 'younger', 'i': 15794},
 {'w': 'worried', 'i': 15873},
 {'w': 'sure', 'i': 15897},
 {'w': 'about', 'i': 17434},
 {'w': 'stupid', 'i': 17464},
 {'w': 'sick', 'i': 17697},
 {'w': 'adult', 'i': 17821},
 {'w': 'person', 'i': 17994},
 {'w': 'woman', 'i': 18821},
 {'w': 'girl', 'i': 18824},
 {'w': 'nervous', 'i': 19456},
 {'w': 'nervous', 'i': 19510},
 {'w': 'sure', 'i': 19662},
 {'w': 'disappointed', 'i': 20461},
 {'w': 'freak', 'i': 20551},
 {'w': 'right', 'i': 20999},
 {'w': 'little', 'i': 25903},
 {'w': 'ready', 'i': 26072},
 {'w': 'sure', 'i': 26263},
 {'w': 'about', 'i': 26950},
 {'w': 'shocked', 'i': 27497},
 {'w': 'mad', 'i': 28687},
 {'w': 'sad', 'i': 28698},
 {'w': 'door', 'i': 30413},
 {'w': 'daughter', 'i': 31272},
 {'w': 'mad', 'i': 31477},
 {'w': 'glad', 'i': 32008},
 {'w': 'disgusted', 'i': 33127},
 {'w': 'glad', 'i': 33151},
 {'w': 'ridiculous', 'i': 34448},
 {'w': 'sorry', 'i': 34738},
 {'w': 'dead', 'i': 36188},
 {'w': 'terrible', 'i': 36949},
 {'w': 'weightless', 'i': 37231},
 {'w': 'able', 'i': 37297},
 {'w': 'alone', 'i': 37922},
 {'w': 'flake', 'i': 38252},
 {'w': 'sure', 'i': 39529},
 {'w': 'mad', 'i': 39862},
 {'w': 'embarrassed', 'i': 39866}]

In [ ]:
book_data["characters"][0]["poss"][:20]

[{'w': 'Avoidance', 'i': 549},
 {'w': 'therapist', 'i': 957},
 {'w': 'knee', 'i': 1074},
 {'w': 'lap', 'i': 1112},
 {'w': 'ticket', 'i': 1140},
 {'w': 'horse', 'i': 1247},
 {'w': 'bus', 'i': 1272},
 {'w': 'nails', 'i': 1539},
 {'w': 'passengers', 'i': 1755},
 {'w': 'suitcase', 'i': 1901},
 {'w': 'mind', 'i': 2246},
 {'w': 'head', 'i': 2291},
 {'w': 'tracks', 'i': 2332},
 {'w': 'suitcase', 'i': 2337},
 {'w': 'heart', 'i': 2344},
 {'w': 'hands', 'i': 2858},
 {'w': 'knees', 'i': 2861},
 {'w': 'hands', 'i': 2890},
 {'w': 'chest', 'i': 2903},
 {'w': 'sketchbook', 'i': 3113}]

In [ ]:
book_data["characters"][0]["id"]

0

In [ ]:
book_data["characters"][0]["g"]

{'inference': {'he/him/his': 0.338,
  'she/her': 0.591,
  'they/them/their': 0.05,
  'xe/xem/xyr/xir': 0.008,
  'ze/zem/zir/hir': 0.013},
 'argmax': 'she/her',
 'max': 0.591,
 'total': 612.689}

In [ ]:
book_data["characters"][0]["count"]

3990

In [ ]:
book_data["characters"][0]["mentions"].keys()

dict_keys(['proper', 'common', 'pronoun'])

In [ ]:
book_data["characters"][0]["mentions"]["proper"]

[]

In [ ]:
book_data["characters"][0]["mentions"]["common"]

[]

In [ ]:
book_data["characters"][0]["mentions"]["pronoun"]

[{'c': 2440, 'n': 'I'},
 {'c': 560, 'n': 'my'},
 {'c': 478, 'n': 'me'},
 {'c': 218, 'n': 'you'},
 {'c': 79, 'n': 'My'},
 {'c': 77, 'n': 'You'},
 {'c': 54, 'n': 'your'},
 {'c': 39, 'n': 'myself'},
 {'c': 18, 'n': 'mine'},
 {'c': 10, 'n': 'Your'},
 {'c': 7, 'n': 'Me'},
 {'c': 2, 'n': 'Mine'},
 {'c': 2, 'n': 'yourself'},
 {'c': 2, 'n': 'yours'},
 {'c': 1, 'n': 'I’d'},
 {'c': 1, 'n': 'ME'},
 {'c': 1, 'n': 'j'},
 {'c': 1, 'n': 'YOUR'}]

# Explore Book Characters in detail

In [ ]:
def get_counter_from_dependency_list(dep_list):
    counter=Counter()
    for token in dep_list:
        term=token["w"]
        tokenGlobalIndex=token["i"]
        counter[term]+=1
    return counter

In [ ]:
for character in data["characters"]:

    agentList=character["agent"]
    patientList=character["patient"]
    possList=character["poss"]
    modList=character["mod"]

    character_id=character["id"]
    count=character["count"]

    referential_gender_distribution=referential_gender_prediction="unknown"

    if character["g"] is not None and character["g"] != "unknown":
        referential_gender_distribution=character["g"]["inference"]
        referential_gender=character["g"]["argmax"]

    mentions=character["mentions"]
    proper_mentions=mentions["proper"]
    max_proper_mention=""

    # just print out information about named characters
    if len(mentions["proper"]) > 0:
        max_proper_mention=mentions["proper"][0]["n"]

        print(character_id, count, max_proper_mention, referential_gender)

        print()
        printTop=10
        for k, v in get_counter_from_dependency_list(possList).most_common(printTop):
            print("\tposs\t%s %s" % (v,k))
        print()
        for k, v in get_counter_from_dependency_list(agentList).most_common(printTop):
            print("\tagent\t%s %s" % (v,k))
        print()
        for k, v in get_counter_from_dependency_list(patientList).most_common(printTop):
            print("\tpatient\t%s %s" % (v,k))
        print()
        for k, v in get_counter_from_dependency_list(modList).most_common(printTop):
            print("\tmod\t%s %s" % (v,k))
        print()

152 1012 Salix she/her

	poss	19 violin
	poss	17 hand
	poss	8 eyes
	poss	7 hands
	poss	5 head
	poss	4 case
	poss	4 fingers
	poss	4 lips
	poss	3 feet
	poss	3 dad

	agent	57 said
	agent	25 know
	agent	25 took
	agent	15 pulled
	agent	15 put
	agent	15 going
	agent	14 ’m
	agent	12 looked
	agent	11 do
	agent	9 did

	patient	6 tell
	patient	5 texted
	patient	5 kissed
	patient	5 meet
	patient	4 Thank
	patient	3 see
	patient	3 texting
	patient	3 Tell
	patient	3 Show
	patient	3 told

	mod	2 person
	mod	2 nice
	mod	2 thing
	mod	1 polite
	mod	1 girl
	mod	1 cute
	mod	1 kind
	mod	1 upset
	mod	1 embarrassed
	mod	1 worried

97 921 Dad he/him/his

	poss	8 phone
	poss	8 face
	poss	6 head
	poss	6 eyes
	poss	6 arm
	poss	5 arms
	poss	5 hand
	poss	5 voice
	poss	5 shoes
	poss	4 truck

	agent	41 said
	agent	22 ’m
	agent	17 going
	agent	10 want
	agent	10 say
	agent	8 have
	agent	8 had
	agent	7 thought
	agent	7 ’re
	agent	6 looked

	patient	5 tell
	patient	4 called
	patient	4 told
	patient	3 call
	patient	3 supposed
	patient	3 kick
	patient	2 find
	patient	2 love
	patient	2 see
	patient	1 tried

	mod	3 dead
	mod	3 asshole
	mod	2 home
	mod	2 reason
	mod	2 king
	mod	1 late
	mod	1 lucky
	mod	1 alone
	mod	1 due
	mod	1 flat

100 859 Claire she/her

	poss	12 belly
	poss	8 head
	poss	5 voice
	poss	5 feet
	poss	4 hand
	poss	4 arms
	poss	3 legs
	poss	3 sandals
	poss	3 lap
	poss	3 eyes

	agent	55 said
	agent	15 put
	agent	13 want
	agent	13 know
	agent	12 have
	agent	12 ’m
	agent	11 went
	agent	10 had
	agent	9 let
	agent	8 made

	patient	10 tell
	patient	4 helped
	patient	4 told
	patient	3 drive
	patient	2 saw
	patient	2 shit
	patient	2 kiss
	patient	2 see
	patient	2 Tell
	patient	2 love

	mod	5 okay
	mod	2 mother
	mod	2 angry
	mod	1 sarcastic
	mod	1 ironic
	mod	1 sweet
	mod	1 nice
	mod	1 pregnant
	mod	1 fine
	mod	1 restless

106 359 Owen he/him/his

	poss	6 head
	poss	4 arms
	poss	4 hand
	poss	3 voice
	poss	3 shirt
	poss	3 dad
	poss	2 ears
	poss	2 hands
	poss	2 arm
	poss	2 feet

	agent	26 said
	agent	5 want
	agent	5 sat
	agent	5 took
	agent	5 know
	agent	4 have
	agent	4 did
	agent	4 asked
	agent	4 wailed
	agent	3 had

	patient	2 Thank
	patient	2 thank
	patient	2 set
	patient	2 pulled
	patient	2 take
	patient	2 helped
	patient	1 scrubbed
	patient	1 ’s
	patient	1 push
	patient	1 picking

	mod	2 dead
	mod	1 blue
	mod	1 limp
	mod	1 smaller
	mod	1 worrier
	mod	1 asleep

90 345 Ruthie she/her

	poss	5 mouth
	poss	4 hands
	poss	2 bedroom
	poss	2 dad
	poss	2 mother
	poss	2 backpack
	poss	2 sandwich
	poss	2 hair
	poss	2 breasts
	poss	2 thighs

	agent	15 said
	agent	5 talking
	agent	4 wanted
	agent	4 sat
	agent	3 had
	agent	3 read
	agent	3 held
	agent	3 stood
	agent	3 kept
	agent	2 get

	patient	7 tell
	patient	5 told
	patient	3 wanted
	patient	2 trust
	patient	2 missed
	patient	2 followed
	patient	2 write
	patient	1 taking
	patient	1 count
	patient	1 saw

	mod	3 interesting
	mod	2 smart
	mod	2 friend
	mod	1 awkward
	mod	1 pleased
	mod	1 one
	mod	1 things
	mod	1 sorry
	mod	1 weird
	mod	1 child

105 311 Corbin he/him/his

	poss	15 arm
	poss	6 cast
	poss	3 hand
	poss	3 mom
	poss	2 leg
	poss	2 brother
	poss	1 bag
	poss	1 pocketknife
	poss	1 shoulders
	poss	1 sister

	agent	30 said
	agent	6 need
	agent	6 hollered
	agent	5 got
	agent	4 pulled
	agent	4 do
	agent	4 going
	agent	4 want
	agent	3 say
	agent	3 ’m

	patient	3 let
	patient	1 spun
	patient	1 seen
	patient	1 join
	patient	1 bring
	patient	1 arranged
	patient	1 wheeled
	patient	1 comforting
	patient	1 stranded
	patient	1 discharged

	mod	2 okay
	mod	1 brat
	mod	1 bitch
	mod	1 about
	mod	1 harsh
	mod	1 baby
	mod	1 impressed
	mod	1 quick

140 236 Maeve she/her

	poss	2 stepmother
	poss	2 time
	poss	2 dad
	poss	1 father
	poss	1 baby
	poss	1 mom
	poss	1 head
	poss	1 neuroses
	poss	1 brothers
	poss	1 Girlfriend

	agent	4 want
	agent	4 know
	agent	3 need
	agent	3 have
	agent	2 ’re
	agent	2 go
	agent	2 take
	agent	2 thinks
	agent	1 moves
	agent	1 falls

	patient	3 Fuck
	patient	2 see
	patient	2 ’s
	patient	2 tell
	patient	2 love
	patient	1 have
	patient	1 sleep
	patient	1 told
	patient	1 got
	patient	1 adopt

	mod	4 okay
	mod	1 cold
	mod	1 one
	mod	1 brilliant

112 234 Mrs. Patel she/her

	poss	5 service
	poss	4 head
	poss	4 cardigan
	poss	4 body
	poss	4 heart
	poss	3 place
	poss	3 hair
	poss	3 chair
	poss	3 home
	poss	2 door

	agent	12 died
	agent	4 have
	agent	3 laughed
	agent	3 gave
	agent	2 wearing
	agent	2 wore
	agent	2 hear
	agent	2 said
	agent	2 liked
	agent	2 needs

	patient	9 killed
	patient	6 found
	patient	3 slumped
	patient	2 saw
	patient	2 finding
	patient	2 bought
	patient	1 told
	patient	1 covered
	patient	1 survived
	patient	1 propped

	mod	4 dead
	mod	3 friend
	mod	1 deaf
	mod	1 old
	mod	1 okay
	mod	1 housekeeper
	mod	1 neighbor

181 141 Mr. Heidelman he/him/his

	poss	3 door
	poss	2 glasses
	poss	2 back
	poss	2 hands
	poss	1 babies
	poss	1 sandwich
	poss	1 mouth
	poss	1 instrument
	poss	1 voice
	poss	1 place

	agent	7 said
	agent	4 nodded
	agent	3 ’m
	agent	3 stood
	agent	3 took
	agent	2 pushed
	agent	2 play
	agent	2 peered
	agent	2 stopped
	agent	2 turned

	patient	2 followed
	patient	2 Thank
	patient	1 Excuse
	patient	1 ushered
	patient	1 thank
	patient	1 take
	patient	1 gone
	patient	1 helped
	patient	1 winded
	patient	1 know

	mod	1 tired
	mod	1 good
	mod	1 okay

96 139 Mom she/her

	poss	6 scarf
	poss	2 friends
	poss	2 car
	poss	2 house
	poss	2 face
	poss	1 clothes
	poss	1 boyfriend
	poss	1 job
	poss	1 garden
	poss	1 all

	agent	8 said
	agent	4 told
	agent	3 got
	agent	3 saw
	agent	3 come
	agent	2 love
	agent	2 going
	agent	2 went
	agent	2 holding
	agent	2 says

	patient	2 ask
	patient	1 sent
	patient	1 mention
	patient	1 reach
	patient	1 invited
	patient	1 told
	patient	1 texted
	patient	1 asked
	patient	1 cc’ing
	patient	1 answer

	mod	1 sorry
	mod	1 asleep
	mod	1 worse
	mod	1 okay
	mod	1 kid

229 138 Pete he/him/his

	poss	3 head
	poss	2 lips
	poss	2 cheeks
	poss	2 necklace
	poss	2 bag
	poss	2 body
	poss	2 eyes
	poss	1 odor
	poss	1 hand
	poss	1 mom

	agent	4 nods
	agent	3 says
	agent	2 looked
	agent	2 say
	agent	2 grew
	agent	2 opens
	agent	2 get
	agent	2 has
	agent	2 feel
	agent	2 sticking

	patient	3 pull
	patient	2 leave
	patient	1 give
	patient	1 see
	patient	1 loses
	patient	1 carry
	patient	1 Show
	patient	1 Tell
	patient	1 take
	patient	1 get

	mod	1 about
	mod	1 tall
	mod	1 alone
	mod	1 taller
	mod	1 heavier
	mod	1 asleep

101 128 Raymond he/him/his

	poss	2 penis
	poss	1 brother
	poss	1 charity
	poss	1 glass
	poss	1 leg
	poss	1 dick
	poss	1 mom
	poss	1 chipper
	poss	1 fault
	poss	1 lungs

	agent	4 know
	agent	3 come
	agent	3 said
	agent	2 went
	agent	2 calling
	agent	2 see
	agent	2 get
	agent	2 says
	agent	2 die
	agent	2 happening

	patient	6 love
	patient	2 told
	patient	1 meet
	patient	1 join
	patient	1 tell
	patient	1 pick
	patient	1 get
	patient	1 calling
	patient	1 covered
	patient	1 saw

	mod	1 asleep
	mod	1 worse
	mod	1 okay
	mod	1 younger

111 128 Jessica she/her

	poss	2 mom
	poss	1 name
	poss	1 house
	poss	1 parents
	poss	1 bedroom
	poss	1 talk
	poss	1 think
	poss	1 clothes
	poss	1 hip
	poss	1 girlfriend

	agent	6 said
	agent	3 moved
	agent	2 had
	agent	2 sat
	agent	2 saw
	agent	2 mapped
	agent	2 laughed
	agent	2 grabbed
	agent	2 found
	agent	2 flicked

	patient	1 figured
	patient	1 ask
	patient	1 tell
	patient	1 met
	patient	1 kissing
	patient	1 gone

	mod	1 bold
	mod	1 amazing
	mod	1 gay

128 99 Grandma she/her

	poss	2 body
	poss	1 wagon
	poss	1 creatures
	poss	1 dog
	poss	1 learner
	poss	1 boys
	poss	1 smile
	poss	1 fist
	poss	1 car
	poss	1 swim

	agent	12 said
	agent	5 want
	agent	3 know
	agent	2 put
	agent	2 handed
	agent	2 told
	agent	2 go
	agent	1 came
	agent	1 left
	agent	1 careened

	patient	2 see
	patient	1 followed
	patient	1 got
	patient	1 visit

	mod	1 silent
	mod	1 happy
	mod	1 full
	mod	1 pissed

104 96 Billy he/him/his

	poss	2 wife
	poss	2 daughter
	poss	2 sons
	poss	2 child
	poss	1 Corbin
	poss	1 obituary
	poss	1 grip
	poss	1 truck
	poss	1 cell
	poss	1 friend

	agent	4 says
	agent	3 died
	agent	3 said
	agent	2 do
	agent	1 leaves
	agent	1 became
	agent	1 hollered
	agent	1 had
	agent	1 grabbed
	agent	1 crushed

	patient	2 needed
	patient	1 found
	patient	1 find
	patient	1 asked
	patient	1 ask
	patient	1 reached

	mod	1 dead
	mod	1 late
	mod	1 fine
	mod	1 head
	mod	1 dad
	mod	1 artist

102 70 Dan he/him/his

	poss	1 clinic
	poss	1 shifts
	poss	1 pajamas
	poss	1 house
	poss	1 place
	poss	1 bed
	poss	1 kit
	poss	1 coop
	poss	1 quota
	poss	1 bedroom

	agent	3 said
	agent	2 offered
	agent	2 liked
	agent	2 made
	agent	2 came
	agent	1 love
	agent	1 spent
	agent	1 handle
	agent	1 taken
	agent	1 trumped

	patient	3 tell
	patient	2 call
	patient	1 visit
	patient	1 see
	patient	1 supposed
	patient	1 followed
	patient	1 told

	mod	1 homebody
	mod	1 cook
	mod	1 nurse

126 51 Hibou she/her

	poss	1 ponytail
	poss	1 wave

	agent	1 says
	agent	1 tucked
	agent	1 vanished
	agent	1 ushering
	agent	1 got
	agent	1 laughed
	agent	1 had
	agent	1 drive
	agent	1 want
	agent	1 end

	patient	5 get
	patient	3 find
	patient	2 gone
	patient	1 sat
	patient	1 hold
	patient	1 lifted
	patient	1 turned
	patient	1 stuffed
	patient	1 stuck
	patient	1 take

	mod	2 girl
	mod	1 nice
	mod	1 head
	mod	1 better
	mod	1 inside

95 36 Nancy she/her

	poss	1 hand
	poss	1 advice
	poss	1 time

	agent	9 said
	agent	3 told
	agent	2 say
	agent	1 offered
	agent	1 drove
	agent	1 know
	agent	1 bought
	agent	1 did
	agent	1 played
	agent	1 recommend

	patient	1 stumped
	patient	1 hear


120 33 King Percival he/him/his

	poss	1 plans
	poss	1 king

	agent	4 ’s
	agent	2 missing
	agent	1 win
	agent	1 fell
	agent	1 go

	patient	5 find
	patient	1 put
	patient	1 take
	patient	1 lost
	patient	1 gone
	patient	1 left
	patient	1 picked


230 21 Gigi she/her

	poss	1 hair
	poss	1 sateen
	poss	1 nails
	poss	1 obsession
	poss	1 prediction

	agent	2 said
	agent	1 smelled
	agent	1 telling
	agent	1 thinks
	agent	1 loved
	agent	1 took
	agent	1 guess
	agent	1 put
	agent	1 used
	agent	1 wrote

	patient	1 chewing

	mod	1 snob
	mod	1 right

138 14 Sherman he/him/his

	poss	2 head
	poss	1 food

	agent	1 wanted
	agent	1 left
	agent	1 smelled
	agent	1 hung
	agent	1 panted
	agent	1 have
	agent	1 drive
	agent	1 sat
	agent	1 headed


	mod	1 silent

210 13 Alice she/her

	poss	1 birth


	patient	1 named
	patient	1 took
	patient	1 born
	patient	1 gave
	patient	1 shifted
	patient	1 get
	patient	1 mean

	mod	1 small

107 12 Deena she/her

	poss	1 ones
	poss	1 man

	agent	1 said
	agent	1 say
	agent	1 did
	agent	1 happened
	agent	1 died
	agent	1 leaves
	agent	1 know

	patient	1 ignoring
	patient	1 avoiding


160 10 Bandhu she/her

	poss	1 uncle

	agent	1 called
	agent	1 ask
	agent	1 said
	agent	1 talking
	agent	1 have
	agent	1 paid
	agent	1 give



92 9 God he/him/his


	agent	1 make
	agent	1 happen

	patient	1 let
	patient	1 thank


99 9 Tim McLean he/him/his

	poss	2 head
	poss	1 flesh

	agent	1 fell
	agent	1 had
	agent	1 sitting
	agent	1 stopped

	patient	1 stabbed


124 9 the Wrens he/him/his


	agent	1 mean
	agent	1 start
	agent	1 ’m
	agent	1 capture
	agent	1 sent



147 9 O’Ryan he/him/his

	poss	1 jaw
	poss	1 bowels
	poss	1 heart

	agent	1 looked
	agent	1 believe


	mod	2 dead

183 9 Linden she/her

	poss	1 audition

	agent	1 ’s
	agent	1 plays
	agent	1 gave
	agent	1 wore
	agent	1 taught


	mod	1 older

98 8 Li he/him/his

	poss	1 seat

	agent	2 went
	agent	1 sat
	agent	1 pulled
	agent	1 stabbed
	agent	1 sawed
	agent	1 paraded
	agent	1 sliced

	patient	1 noticed
	patient	1 done


135 8 Dorothy she/her





157 8 Daddy they/them/their


	agent	2 ’re

	patient	2 need


173 8 Django Reinhardt he/him/his

	poss	1 stuff

	agent	2 wants
	agent	1 called
	agent	1 listening
	agent	1 tell

	patient	1 loves


195 8 Honey he/him/his

	poss	2 dad

	agent	1 want
	agent	1 stay
	agent	1 know
	agent	1 having

	patient	1 Love


117 7 Joel Plaskett he/him/his

	poss	1 boots
	poss	1 music

	agent	1 kicking
	agent	1 get


	mod	1 entitled
	mod	1 musician

121 7 King Wren he/him/his


	agent	1 plotting
	agent	1 win


	mod	1 king

86 6 Carrie Mac she/her





164 6 Louis Armstrong he/him/his


	agent	1 died

	patient	1 knows

	mod	1 kid
	mod	1 janitor
	mod	1 old

93 5 Carol Epperly she/her


	agent	1 stepping



139 5 Gillian Glover she/her

	poss	2 granddaughter
	poss	1 grandchildren
	poss	1 grandsons
	poss	1 Corbin




145 5 Kelly she/her


	agent	1 wanted

	patient	1 trust

	mod	1 editor

197 5 Baby she/her

	poss	1 magic

	agent	1 need



212 5 Christianne she/her

	poss	1 Lyceum
	poss	1 programs
	poss	1 magic



	mod	1 mother

103 4 Disappointment he/him/his


	agent	1 stayed
	agent	1 crawl



165 4 Mia Wong she/her

	poss	1 party

	agent	2 died
	agent	1 had



169 4 Braxton Hicks he/him/his





155 3 the Percivals they/them/their





168 3 Nigel he/him/his


	agent	1 understand



193 3 Maevey he/him/his


	agent	1 ’re



205 3 Brava he/him/his


	agent	1 took



207 3 Theoretically he/him/his

	poss	1 mind

	agent	1 changed



225 3 Jess Regel she/her


	agent	1 does



88 2 Ember he/him/his


	agent	1 Published

	patient	1 published


10 2 Vancouver they/them/their


	agent	1 had
	agent	1 existed



119 2 Prince she/her



	patient	1 painted


122 2 Babies he/him/his

	poss	1 rates


	patient	1 stuck


148 2 Hank he/him/his





170 2 Beethoven he/him/his

	poss	1 Concerto




175 2 Hope she/her

	poss	1 future

	agent	1 died



180 2 Oscar Heidelman he/him/his





203 2 AJ she/her




	mod	1 blip

209 2 Easy she/her


	agent	1 does
	agent	1 do

In [ ]:
df_list = []
for character in data["characters"]:

    agentList = character["agent"]
    patientList = character["patient"]
    possList = character["poss"]
    modList = character["mod"]
    character_id = character["id"]
    count = character["count"]
    referential_gender_distribution = referential_gender_prediction="unknown"

    if character["g"] is not None and character["g"] != "unknown":
        referential_gender_distribution=character["g"]["inference"]
        referential_gender=character["g"]["argmax"]

    mentions=character["mentions"]
    proper_mentions=mentions["proper"]
    max_proper_mention=""

    # just print out information about named characters
    if len(mentions["proper"]) > 0:
        max_proper_mention=mentions["proper"][0]["n"]

        df_list.append( {'Name':max_proper_mention , 'Character ID': character_id,
                         'Mentions': count,
                       'Gender': referential_gender,
                       'Possessives': get_counter_from_dependency_list(possList).most_common(10),
                       'Agent': get_counter_from_dependency_list(agentList).most_common(10),
                       'Patient': get_counter_from_dependency_list(patientList).most_common(10),
                       'Modifiers': get_counter_from_dependency_list(modList).most_common(10)}
        )
df = pd.DataFrame(df_list)
df['Character ID'] = df['Character ID'].astype(str)
df

,Name,Character ID,Mentions,Gender,Possessives,Agent,Patient,Modifiers
0,Salix,152,1012,she/her,"[(violin, 19), (hand, 17), (eyes, 8), (hands, ...","[(said, 57), (know, 25), (took, 25), (pulled, ...","[(tell, 6), (texted, 5), (kissed, 5), (meet, 5...","[(person, 2), (nice, 2), (thing, 2), (polite, ..."
1,Dad,97,921,he/him/his,"[(phone, 8), (face, 8), (head, 6), (eyes, 6), ...","[(said, 41), (’m, 22), (going, 17), (want, 10)...","[(tell, 5), (called, 4), (told, 4), (call, 3),...","[(dead, 3), (asshole, 3), (home, 2), (reason, ..."
2,Claire,100,859,she/her,"[(belly, 12), (head, 8), (voice, 5), (feet, 5)...","[(said, 55), (put, 15), (want, 13), (know, 13)...","[(tell, 10), (helped, 4), (told, 4), (drive, 3...","[(okay, 5), (mother, 2), (angry, 2), (sarcasti..."
3,Owen,106,359,he/him/his,"[(head, 6), (arms, 4), (hand, 4), (voice, 3), ...","[(said, 26), (want, 5), (sat, 5), (took, 5), (...","[(Thank, 2), (thank, 2), (set, 2), (pulled, 2)...","[(dead, 2), (blue, 1), (limp, 1), (smaller, 1)..."
4,Ruthie,90,345,she/her,"[(mouth, 5), (hands, 4), (bedroom, 2), (dad, 2...","[(said, 15), (talking, 5), (wanted, 4), (sat, ...","[(tell, 7), (told, 5), (wanted, 3), (trust, 2)...","[(interesting, 3), (smart, 2), (friend, 2), (a..."
...,...,...,...,...,...,...,...,...
57,Beethoven,170,2,he/him/his,"[(Concerto, 1)]",[],[],[]
58,Hope,175,2,she/her,"[(future, 1)]","[(died, 1)]",[],[]
59,Oscar Heidelman,180,2,he/him/his,[],[],[],[]
60,AJ,203,2,she/her,[],[],[],"[(blip, 1)]"
61,Easy,209,2,she/her,[],"[(does, 1), (do, 1)]",[],[]

In [ ]:
# Load quotation data
quote_df = pd.read_csv("/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.quotes", delimiter='\t')
quote_df['char_id'] = quote_df['char_id'].astype(str)
quote_df = pd.merge(df[['Character ID', 'Name']], quote_df, left_on = 'Character ID', right_on= 'char_id')

In [ ]:
quote_df.sort_values(by='quote_start')[:100]

,Character ID,Name,quote_start,quote_end,mention_start,mention_end,mention_phrase,char_id,quote
1546,95,Nancy,1059,1066,1067,1067,She,95,"“ Oh , Maeve , sweetheart . ”"
1547,95,Nancy,1076,1086,1070,1070,her,95,“ It will be okay . I know it . ”
1420,96,Mom,1155,1160,1161,1161,Mom,96,"“ I love you , ”"
1421,96,Mom,1164,1169,1161,1161,Mom,96,“ I love you . ”
1552,103,Disappointment,4160,4173,4115,4115,Disappointment,103,“ What if I stayed at Dan ’s place the whole t...
...,...,...,...,...,...,...,...,...,...
500,97,Dad,8525,8530,8520,8520,he,97,“ They ’re beautiful . ”
501,97,Dad,8607,8625,8582,8582,he,97,"“ When you come in the summer , to stay , your..."
1422,96,Mom,10880,10884,10855,10855,She,96,“ proper hello . ”
1458,101,Raymond,11115,11118,11119,11119,Raymond,101,“ Maeve ! ”
1459,101,Raymond,11138,11152,11128,11128,He,101,"“ I certainly did n’t see you there . Uh , goo..."

# Entities Exploration

In [ ]:
entity_df = pd.read_csv("/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.entities", delimiter='\t')
entity_df

       COREF  start_token  end_token  prop  cat            text
0         86            2          3  PROP  PER      CARRIE MAC
1        234           25         26   NOM  PER      the author
2        235           37         38   NOM  PER  actual persons
3         86           57         58  PROP  PER      Carrie Mac
4         86           74         75  PROP  PER      Carrie Mac
...      ...          ...        ...   ...  ...             ...
15032   2814        94394      94394  PRON  PER             our
15033   2814        94405      94405  PRON  PER              We
15034   2815        94432      94432  PRON  PER            your
15035   2815        94437      94437  PRON  PER            your
15036   2816        94454      94455   NOM  PER     this author

[15037 rows x 6 columns]

In [ ]:
entity_df['cat'].value_counts()

PER    13477
FAC      910
VEH      252
GPE      198
LOC      177
ORG       23
Name: cat, dtype: int64

# Get Locations

In [ ]:
entity_filter = entity_df['cat'] == 'LOC'
entity_df[entity_filter]['text'].value_counts().reset_index().rename(columns={'index':'entity'})

                  entity  text
0              the beach    15
1               the lake    14
2              the water    11
3              the world     9
4             Alice Lake     7
..                   ...   ...
93  Nowhere near Gastown     1
94      the Fraser River     1
95  the edge of the park     1
96  the edge of the road     1
97            the valley     1

[98 rows x 2 columns]

# Get People

In [ ]:
entity_filter = entity_df['cat'] == 'PER'
entity_df[entity_filter]['text'].value_counts().reset_index().rename(columns={'index':'entity'})[:50]

           entity  text
0               I  3056
1             her   760
2             you   716
3              my   621
4              me   579
5             she   459
6              he   443
7             She   406
8             his   355
9              He   326
10         Claire   316
11          Salix   315
12            You   248
13             we   239
14            him   229
15            Dad   225
16             We   149
17          Maeve   146
18           your   145
19           they   141
20           Owen   139
21         Corbin   138
22         Ruthie   110
23             My   100
24             us    99
25           them    97
26     Mrs. Patel    90
27          their    84
28       the boys    72
29            Mom    72
30            our    55
31  Mr. Heidelman    50
32        Jessica    49
33       the baby    48
34        Raymond    45
35         myself    44
36           They    44
37        Grandma    39
38            Dan    34
39            Her    32
40            His    31
41          Billy    30
42       The boys    28
43           Pete    28
44         my mom    26
45           Your    26
46         my dad    25
47         people    23
48        herself    22
49        someone    22

# Get Geopolitical entities

In [ ]:
entity_filter = entity_df['cat'] == 'GPE'
entity_df[entity_filter]['text'].value_counts().reset_index().rename(columns={'index':'entity'})[:50]

                                 entity  text
0                                 Haiti    27
1                         Port Townsend    15
2                              the city    12
3                             Vancouver    11
4                               Seattle    10
5                           Gnomenville     8
6                              Thailand     8
7                             Juilliard     8
8                           Continental     6
9                            California     6
10                             East Van     6
11                             New York     5
12                             Squamish     5
13                                there     4
14                               Canada     3
15                              Gastown     3
16                          the country     2
17                               London     2
18                              Chicago     2
19                              Windsor     2
20                           Strathcona     2
21                              Gibsons     2
22                                 Brit     2
23                                 ASRA     2
24                                 here     2
25                           big cities     2
26                              Everett     2
27                               a town     1
28                   Port - au - Prince     1
29                                  Sea     1
30                                  Sky     1
31                the middle of nowhere     1
32                    Hostile territory     1
33                           Alice Lake     1
34                               Behold     1
35                              Beaches     1
36       the Percival and Wren kingdoms     1
37                 University of Alaska     1
38                            Fairbanks     1
39                                 town     1
40                                Knopf     1
41                            Hollywood     1
42                              Bangkok     1
43                               cities     1
44                            Australia     1
45                               Europe     1
46                              Raymond     1
47                           that place     1
48  some random neighborhood in Chicago     1
49                           Craigslist     1

# Get Facilities

In [ ]:
entity_filter = entity_df['cat'] == 'FAC'
entity_df[entity_filter]['text'].value_counts().reset_index().rename(columns={'index':'entity'})[:50]

                entity  text
0                 home   106
1                there    26
2           the street    26
3             the park    24
4         the hospital    23
5                 here    19
6             the road    15
7           the stairs    15
8      the parking lot    15
9             upstairs    14
10            the room    14
11     the bus station    12
12           the alley    12
13        the sidewalk    12
14          the garden    11
15         the kitchen    11
16                  it     9
17          downstairs     9
18              school     8
19           the house     8
20         the airport     7
21           the porch     7
22         the highway     7
23     the living room     7
24       the courtyard     7
25            the tent     7
26      the playground     6
27                  It     6
28        the building     5
29        the bathroom     5
30            the hall     5
31            the dock     5
32           the trail     5
33           the ferry     5
34           this tent     4
35            downtown     4
36            the path     4
37  the ferry terminal     4
38             my room     4
39            the deck     4
40         the trailer     3
41          the closet     3
42            Upstairs     3
43    the liquor store     3
44           her house     3
45      the spray park     3
46        the terminal     3
47           his house     3
48       a parking lot     3
49            the ramp     3

# Get Vehicles

In [ ]:
entity_filter = entity_df['cat'] == 'VEH'
entity_df[entity_filter]['text'].value_counts().reset_index().rename(columns={'index':'entity'})[:50]

                           entity  text
0                         the van    32
1                         the bus    18
2                       the train    15
3                         the car    13
4                       the ferry    12
5                       the truck     9
6                       the wagon     9
7                   the ambulance     8
8                           a bus     7
9                        the boat     5
10                     your truck     4
11                   a fire truck     4
12                        a plane     4
13                 the next ferry     3
14                   an ambulance     3
15                        her car     3
16                           cars     3
17                    those boats     2
18                        a ferry     2
19                          a car     2
20                        The bus     2
21                         a bike     2
22                a Greyhound bus     2
23                   The next car     1
24               the moving truck     1
25                        A truck     1
26                          A car     1
27  a great big yellow school bus     1
28                   a parked car     1
29                 a moving truck     1
30                       my truck     1
31                A garbage truck     1
32                          A bus     1
33                            bus     1
34                    those buses     1
35          A bright yellow truck     1
36                      airplanes     1
37                      The wagon     1
38                    car crashes     1
39                the night buses     1
40                         A boat     1
41                          a van     1
42                   An ambulance     1
43                   a filthy van     1
44                   the backseat     1
45              The plastic wagon     1
46               A delivery truck     1
47                       that van     1
48                      The train     1
49       The train speeding along     1

# Analysis

See for more: https://booknlp.pythonhumanities.com/04_character_analysis.html

In [ ]:
import json
from collections import Counter

In [ ]:
def proc(filename):
    with open(filename) as file:
        data=json.load(file)
    return data

In [ ]:
def get_counter_from_dependency_list(dep_list):
    counter=Counter()
    for token in dep_list:
        term=token["w"]
        tokenGlobalIndex=token["i"]
        counter[term]+=1
    return counter

In [ ]:
#data=proc("x")

In [ ]:
def create_character_data(data, printTop):
    character_data = {}
    for character in data["characters"]:

        agentList=character["agent"]
        patientList=character["patient"]
        possList=character["poss"]
        modList=character["mod"]

        character_id=character["id"]
        count=character["count"]

        referential_gender_distribution=referential_gender_prediction="unknown"

        if character["g"] is not None and character["g"] != "unknown":
            referential_gender_distribution=character["g"]["inference"]
            referential_gender=character["g"]["argmax"]

        mentions=character["mentions"]
        proper_mentions=mentions["proper"]
        max_proper_mention=""

        #Let's create some empty lists that we can append to.
        poss_items = []
        agent_items = []
        patient_items = []
        mod_items = []

        # just print out information about named characters
        if len(mentions["proper"]) > 0:
            max_proper_mention=mentions["proper"][0]["n"]
            for k, v in get_counter_from_dependency_list(possList).most_common(printTop):
                poss_items.append((v,k))

            for k, v in get_counter_from_dependency_list(agentList).most_common(printTop):
                agent_items.append((v,k))

            for k, v in get_counter_from_dependency_list(patientList).most_common(printTop):
                patient_items.append((v,k))

            for k, v in get_counter_from_dependency_list(modList).most_common(printTop):
                mod_items.append((v,k))




            # print(character_id, count, max_proper_mention, referential_gender)
            character_data[character_id] = {"id": character_id,
                                  "count": count,
                                  "max_proper_mention": max_proper_mention,
                                  "referential_gender": referential_gender,
                                  "possList": poss_items,
                                  "agentList": agent_items,
                                  "patientList": patient_items,
                                  "modList": mod_items
                                 }

    return character_data

In [ ]:
character_data = create_character_data(data, 10)

In [ ]:
print (character_data[98])

{'id': 98, 'count': 8, 'max_proper_mention': 'Li', 'referential_gender': 'he/him/his', 'possList': [(1, 'seat')], 'agentList': [(2, 'went'), (1, 'sat'), (1, 'pulled'), (1, 'stabbed'), (1, 'sawed'), (1, 'paraded'), (1, 'sliced')], 'patientList': [(1, 'noticed'), (1, 'done')], 'modList': []}

In [ ]:
def find_verb_usage(data, analysis=["agent", "patient"]):
    new_analysis = []
    for item in analysis:
        if item == "agent":
            new_analysis.append("agentList")
        elif item == "patient":
            new_analysis.append("patientList")
    main_agents = {}
    main_patients = {}
    for character in character_data:
        temp_data = character_data[character]
        for item in new_analysis:
            for verb in temp_data[item]:
                verb = verb[1].lower()
                if item == "agentList":
                    if verb not in main_agents:
                        main_agents[verb] = [(character, temp_data["max_proper_mention"])]
                    else:
                        main_agents[verb].append((character, temp_data["max_proper_mention"]))
                elif item == "patientList":
                    if verb not in main_patients:
                        main_patients[verb] = [(character, temp_data["max_proper_mention"])]
                    else:
                        main_patients[verb].append((character, temp_data["max_proper_mention"]))
    verb_usage = {"agent": main_agents,
                 "patient": main_patients}
    return verb_usage

In [ ]:
verb_data = find_verb_usage(data)
verb_data

{'agent': {'said': [(152, 'Salix'),
   (97, 'Dad'),
   (100, 'Claire'),
   (106, 'Owen'),
   (90, 'Ruthie'),
   (105, 'Corbin'),
   (112, 'Mrs. Patel'),
   (181, 'Mr. Heidelman'),
   (96, 'Mom'),
   (101, 'Raymond'),
   (111, 'Jessica'),
   (128, 'Grandma'),
   (104, 'Billy'),
   (102, 'Dan'),
   (95, 'Nancy'),
   (230, 'Gigi'),
   (107, 'Deena'),
   (160, 'Bandhu')],
  'know': [(152, 'Salix'),
   (100, 'Claire'),
   (106, 'Owen'),
   (140, 'Maeve'),
   (101, 'Raymond'),
   (128, 'Grandma'),
   (95, 'Nancy'),
   (107, 'Deena'),
   (195, 'Honey')],
  'took': [(152, 'Salix'),
   (106, 'Owen'),
   (181, 'Mr. Heidelman'),
   (230, 'Gigi'),
   (205, 'Brava')],
  'pulled': [(152, 'Salix'), (105, 'Corbin'), (98, 'Li')],
  'put': [(152, 'Salix'), (100, 'Claire'), (128, 'Grandma'), (230, 'Gigi')],
  'going': [(152, 'Salix'), (97, 'Dad'), (105, 'Corbin'), (96, 'Mom')],
  '’m': [(152, 'Salix'),
   (97, 'Dad'),
   (100, 'Claire'),
   (105, 'Corbin'),
   (181, 'Mr. Heidelman'),
   (124, 'the Wrens')],
  'looked': [(152, 'Salix'), (97, 'Dad'), (229, 'Pete'), (147, 'O’Ryan')],
  'do': [(152, 'Salix'), (105, 'Corbin'), (104, 'Billy'), (209, 'Easy')],
  'did': [(152, 'Salix'), (106, 'Owen'), (95, 'Nancy'), (107, 'Deena')],
  'want': [(97, 'Dad'),
   (100, 'Claire'),
   (106, 'Owen'),
   (105, 'Corbin'),
   (140, 'Maeve'),
   (128, 'Grandma'),
   (126, 'Hibou'),
   (195, 'Honey')],
  'say': [(97, 'Dad'),
   (105, 'Corbin'),
   (229, 'Pete'),
   (95, 'Nancy'),
   (107, 'Deena')],
  'have': [(97, 'Dad'),
   (100, 'Claire'),
   (106, 'Owen'),
   (140, 'Maeve'),
   (112, 'Mrs. Patel'),
   (138, 'Sherman'),
   (160, 'Bandhu')],
  'had': [(97, 'Dad'),
   (100, 'Claire'),
   (106, 'Owen'),
   (90, 'Ruthie'),
   (111, 'Jessica'),
   (104, 'Billy'),
   (126, 'Hibou'),
   (99, 'Tim McLean'),
   (165, 'Mia Wong'),
   (10, 'Vancouver')],
  'thought': [(97, 'Dad')],
  '’re': [(97, 'Dad'), (140, 'Maeve'), (157, 'Daddy'), (193, 'Maevey')],
  'went': [(100, 'Claire'), (96, 'Mom'), (101, 'Raymond'), (98, 'Li')],
  'let': [(100, 'Claire')],
  'made': [(100, 'Claire'), (102, 'Dan')],
  'sat': [(106, 'Owen'),
   (90, 'Ruthie'),
   (111, 'Jessica'),
   (138, 'Sherman'),
   (98, 'Li')],
  'asked': [(106, 'Owen')],
  'wailed': [(106, 'Owen')],
  'talking': [(90, 'Ruthie'), (160, 'Bandhu')],
  'wanted': [(90, 'Ruthie'), (138, 'Sherman'), (145, 'Kelly')],
  'read': [(90, 'Ruthie')],
  'held': [(90, 'Ruthie')],
  'stood': [(90, 'Ruthie'), (181, 'Mr. Heidelman')],
  'kept': [(90, 'Ruthie')],
  'get': [(90, 'Ruthie'),
   (229, 'Pete'),
   (101, 'Raymond'),
   (117, 'Joel Plaskett')],
  'need': [(105, 'Corbin'), (140, 'Maeve'), (197, 'Baby')],
  'hollered': [(105, 'Corbin'), (104, 'Billy')],
  'got': [(105, 'Corbin'), (96, 'Mom'), (126, 'Hibou')],
  'go': [(140, 'Maeve'), (128, 'Grandma'), (120, 'King Percival')],
  'take': [(140, 'Maeve')],
  'thinks': [(140, 'Maeve'), (230, 'Gigi')],
  'moves': [(140, 'Maeve')],
  'falls': [(140, 'Maeve')],
  'died': [(112, 'Mrs. Patel'),
   (104, 'Billy'),
   (107, 'Deena'),
   (164, 'Louis Armstrong'),
   (165, 'Mia Wong'),
   (175, 'Hope')],
  'laughed': [(112, 'Mrs. Patel'), (111, 'Jessica'), (126, 'Hibou')],
  'gave': [(112, 'Mrs. Patel'), (183, 'Linden')],
  'wearing': [(112, 'Mrs. Patel')],
  'wore': [(112, 'Mrs. Patel'), (183, 'Linden')],
  'hear': [(112, 'Mrs. Patel')],
  'liked': [(112, 'Mrs. Patel'), (102, 'Dan')],
  'needs': [(112, 'Mrs. Patel')],
  'nodded': [(181, 'Mr. Heidelman')],
  'pushed': [(181, 'Mr. Heidelman')],
  'play': [(181, 'Mr. Heidelman')],
  'peered': [(181, 'Mr. Heidelman')],
  'stopped': [(181, 'Mr. Heidelman'), (99, 'Tim McLean')],
  'turned': [(181, 'Mr. Heidelman')],
  'told': [(96, 'Mom'), (128, 'Grandma'), (95, 'Nancy')],
  'saw': [(96, 'Mom'), (111, 'Jessica')],
  'come': [(96, 'Mom'), (101, 'Raymond')],
  'love': [(96, 'Mom'), (102, 'Dan')],
  'holding': [(96, 'Mom')],
  'says': [(96, 'Mom'),
   (229, 'Pete'),
   (101, 'Raymond'),
   (104, 'Billy'),
   (126, 'Hibou')],
  'nods': [(229, 'Pete')],
  'grew': [(229, 'Pete')],
  'opens': [(229, 'Pete')],
  'has': [(229, 'Pete')],
  'feel': [(229, 'Pete')],
  'sticking': [(229, 'Pete')],
  'calling': [(101, 'Raymond')],
  'see': [(101, 'Raymond')],
  'die': [(101, 'Raymond')],
  'happening': [(101, 'Raymond')],
  'moved': [(111, 'Jessica')],
  'mapped': [(111, 'Jessica')],
  'grabbed': [(111, 'Jessica'), (104, 'Billy')],
  'found': [(111, 'Jessica')],
  'flicked': [(111, 'Jessica')],
  'handed': [(128, 'Grandma')],
  'came': [(128, 'Grandma'), (102, 'Dan')],
  'left': [(128, 'Grandma'), (138, 'Sherman')],
  'careened': [(128, 'Grandma')],
  'leaves': [(104, 'Billy'), (107, 'Deena')],
  'became': [(104, 'Billy')],
  'crushed': [(104, 'Billy')],
  'offered': [(102, 'Dan'), (95, 'Nancy')],
  'spent': [(102, 'Dan')],
  'handle': [(102, 'Dan')],
  'taken': [(102, 'Dan')],
  'trumped': [(102, 'Dan')],
  'tucked': [(126, 'Hibou')],
  'vanished': [(126, 'Hibou')],
  'ushering': [(126, 'Hibou')],
  'drive': [(126, 'Hibou'), (138, 'Sherman')],
  'end': [(126, 'Hibou')],
  'drove': [(95, 'Nancy')],
  'bought': [(95, 'Nancy')],
  'played': [(95, 'Nancy')],
  'recommend': [(95, 'Nancy')],
  '’s': [(120, 'King Percival'), (183, 'Linden')],
  'missing': [(120, 'King Percival')],
  'win': [(120, 'King Percival'), (121, 'King Wren')],
  'fell': [(120, 'King Percival'), (99, 'Tim McLean')],
  'smelled': [(230, 'Gigi'), (138, 'Sherman')],
  'telling': [(230, 'Gigi')],
  'loved': [(230, 'Gigi')],
  'guess': [(230, 'Gigi')],
  'used': [(230, 'Gigi')],
  'wrote': [(230, 'Gigi')],
  'hung': [(138, 'Sherman')],
  'panted': [(138, 'Sherman')],
  'headed': [(138, 'Sherman')],
  'happened': [(107, 'Deena')],
  'called': [(160, 'Bandhu'), (173, 'Django Reinhardt')],
  'ask': [(160, 'Bandhu')],
  'paid': [(160, 'Bandhu')],
  'give': [(160, 'Bandhu')],
  'make': [(92, 'God')],
  'happen': [(92, 'God')],
  'sitting': [(99, 'Tim McLean')],
  'mean': [(124, 'the Wrens')],
  'start': [(124, 'the Wrens')],
  'capture': [(124, 'the Wrens')],
  'sent': [(124, 'the Wrens')],
  'believe': [(147, 'O’Ryan')],
  'plays': [(183, 'Linden')],
  'taught': [(183, 'Linden')],
  'stabbed': [(98, 'Li')],
  'sawed': [(98, 'Li')],
  'paraded': [(98, 'Li')],
  'sliced': [(98, 'Li')],
  'wants': [(173, 'Django Reinhardt')],
  'listening': [(173, 'Django Reinhardt')],
  'tell': [(173, 'Django Reinhardt')],
  'stay': [(195, 'Honey')],
  'having': [(195, 'Honey')],
  'kicking': [(117, 'Joel Plaskett')],
  'plotting': [(121, 'King Wren')],
  'stepping': [(93, 'Carol Epperly')],
  'stayed': [(103, 'Disappointment')],
  'crawl': [(103, 'Disappointment')],
  'understand': [(168, 'Nigel')],
  'changed': [(207, 'Theoretically')],
  'does': [(225, 'Jess Regel'), (209, 'Easy')],
  'published': [(88, 'Ember')],
  'existed': [(10, 'Vancouver')]},
 'patient': {'tell': [(152, 'Salix'),
   (152, 'Salix'),
   (97, 'Dad'),
   (100, 'Claire'),
   (100, 'Claire'),
   (90, 'Ruthie'),
   (140, 'Maeve'),
   (229, 'Pete'),
   (101, 'Raymond'),
   (111, 'Jessica'),
   (102, 'Dan')],
  'texted': [(152, 'Salix'), (96, 'Mom')],
  'kissed': [(152, 'Salix')],
  'meet': [(152, 'Salix'), (101, 'Raymond')],
  'thank': [(152, 'Salix'),
   (106, 'Owen'),
   (106, 'Owen'),
   (181, 'Mr. Heidelman'),
   (181, 'Mr. Heidelman'),
   (92, 'God')],
  'see': [(152, 'Salix'),
   (97, 'Dad'),
   (100, 'Claire'),
   (140, 'Maeve'),
   (229, 'Pete'),
   (128, 'Grandma'),
   (102, 'Dan')],
  'texting': [(152, 'Salix')],
  'show': [(152, 'Salix'), (229, 'Pete')],
  'told': [(152, 'Salix'),
   (97, 'Dad'),
   (100, 'Claire'),
   (90, 'Ruthie'),
   (140, 'Maeve'),
   (112, 'Mrs. Patel'),
   (96, 'Mom'),
   (101, 'Raymond'),
   (102, 'Dan')],
  'called': [(97, 'Dad')],
  'call': [(97, 'Dad'), (102, 'Dan')],
  'supposed': [(97, 'Dad'), (102, 'Dan')],
  'kick': [(97, 'Dad')],
  'find': [(97, 'Dad'),
   (104, 'Billy'),
   (126, 'Hibou'),
   (120, 'King Percival')],
  'love': [(97, 'Dad'),
   (100, 'Claire'),
   (140, 'Maeve'),
   (101, 'Raymond'),
   (195, 'Honey')],
  'tried': [(97, 'Dad')],
  'helped': [(100, 'Claire'), (106, 'Owen'), (181, 'Mr. Heidelman')],
  'drive': [(100, 'Claire')],
  'saw': [(100, 'Claire'),
   (90, 'Ruthie'),
   (112, 'Mrs. Patel'),
   (101, 'Raymond')],
  'shit': [(100, 'Claire')],
  'kiss': [(100, 'Claire')],
  'set': [(106, 'Owen')],
  'pulled': [(106, 'Owen')],
  'take': [(106, 'Owen'),
   (181, 'Mr. Heidelman'),
   (229, 'Pete'),
   (126, 'Hibou'),
   (120, 'King Percival')],
  'scrubbed': [(106, 'Owen')],
  '’s': [(106, 'Owen'), (140, 'Maeve')],
  'push': [(106, 'Owen')],
  'picking': [(106, 'Owen')],
  'wanted': [(90, 'Ruthie')],
  'trust': [(90, 'Ruthie'), (145, 'Kelly')],
  'missed': [(90, 'Ruthie')],
  'followed': [(90, 'Ruthie'),
   (181, 'Mr. Heidelman'),
   (128, 'Grandma'),
   (102, 'Dan')],
  'write': [(90, 'Ruthie')],
  'taking': [(90, 'Ruthie')],
  'count': [(90, 'Ruthie')],
  'let': [(105, 'Corbin'), (92, 'God')],
  'spun': [(105, 'Corbin')],
  'seen': [(105, 'Corbin')],
  'join': [(105, 'Corbin'), (101, 'Raymond')],
  'bring': [(105, 'Corbin')],
  'arranged': [(105, 'Corbin')],
  'wheeled': [(105, 'Corbin')],
  'comforting': [(105, 'Corbin')],
  'stranded': [(105, 'Corbin')],
  'discharged': [(105, 'Corbin')],
  'fuck': [(140, 'Maeve')],
  'have': [(140, 'Maeve')],
  'sleep': [(140, 'Maeve')],
  'got': [(140, 'Maeve'), (128, 'Grandma')],
  'adopt': [(140, 'Maeve')],
  'killed': [(112, 'Mrs. Patel')],
  'found': [(112, 'Mrs. Patel'), (104, 'Billy')],
  'slumped': [(112, 'Mrs. Patel')],
  'finding': [(112, 'Mrs. Patel')],
  'bought': [(112, 'Mrs. Patel')],
  'covered': [(112, 'Mrs. Patel'), (101, 'Raymond')],
  'survived': [(112, 'Mrs. Patel')],
  'propped': [(112, 'Mrs. Patel')],
  'excuse': [(181, 'Mr. Heidelman')],
  'ushered': [(181, 'Mr. Heidelman')],
  'gone': [(181, 'Mr. Heidelman'),
   (111, 'Jessica'),
   (126, 'Hibou'),
   (120, 'King Percival')],
  'winded': [(181, 'Mr. Heidelman')],
  'know': [(181, 'Mr. Heidelman')],
  'ask': [(96, 'Mom'), (111, 'Jessica'), (104, 'Billy')],
  'sent': [(96, 'Mom')],
  'mention': [(96, 'Mom')],
  'reach': [(96, 'Mom')],
  'invited': [(96, 'Mom')],
  'asked': [(96, 'Mom'), (104, 'Billy')],
  'cc’ing': [(96, 'Mom')],
  'answer': [(96, 'Mom')],
  'pull': [(229, 'Pete')],
  'leave': [(229, 'Pete')],
  'give': [(229, 'Pete')],
  'loses': [(229, 'Pete')],
  'carry': [(229, 'Pete')],
  'get': [(229, 'Pete'), (101, 'Raymond'), (126, 'Hibou'), (210, 'Alice')],
  'pick': [(101, 'Raymond')],
  'calling': [(101, 'Raymond')],
  'figured': [(111, 'Jessica')],
  'met': [(111, 'Jessica')],
  'kissing': [(111, 'Jessica')],
  'visit': [(128, 'Grandma'), (102, 'Dan')],
  'needed': [(104, 'Billy')],
  'reached': [(104, 'Billy')],
  'sat': [(126, 'Hibou')],
  'hold': [(126, 'Hibou')],
  'lifted': [(126, 'Hibou')],
  'turned': [(126, 'Hibou')],
  'stuffed': [(126, 'Hibou')],
  'stuck': [(126, 'Hibou'), (122, 'Babies')],
  'stumped': [(95, 'Nancy')],
  'hear': [(95, 'Nancy')],
  'put': [(120, 'King Percival')],
  'lost': [(120, 'King Percival')],
  'left': [(120, 'King Percival')],
  'picked': [(120, 'King Percival')],
  'chewing': [(230, 'Gigi')],
  'named': [(210, 'Alice')],
  'took': [(210, 'Alice')],
  'born': [(210, 'Alice')],
  'gave': [(210, 'Alice')],
  'shifted': [(210, 'Alice')],
  'mean': [(210, 'Alice')],
  'ignoring': [(107, 'Deena')],
  'avoiding': [(107, 'Deena')],
  'stabbed': [(99, 'Tim McLean')],
  'noticed': [(98, 'Li')],
  'done': [(98, 'Li')],
  'need': [(157, 'Daddy')],
  'loves': [(173, 'Django Reinhardt')],
  'knows': [(164, 'Louis Armstrong')],
  'published': [(88, 'Ember')],
  'painted': [(119, 'Prince')]}}

In [ ]:
verb_data["agent"]["said"]

[(152, 'Salix'),
 (97, 'Dad'),
 (100, 'Claire'),
 (106, 'Owen'),
 (90, 'Ruthie'),
 (105, 'Corbin'),
 (112, 'Mrs. Patel'),
 (181, 'Mr. Heidelman'),
 (96, 'Mom'),
 (101, 'Raymond'),
 (111, 'Jessica'),
 (128, 'Grandma'),
 (104, 'Billy'),
 (102, 'Dan'),
 (95, 'Nancy'),
 (230, 'Gigi'),
 (107, 'Deena'),
 (160, 'Bandhu')]

In [ ]:
verb_data["agent"]["looked"]

[(152, 'Salix'), (97, 'Dad'), (229, 'Pete'), (147, 'O’Ryan')]

# Events Analysis

In [ ]:
import pandas as pd
df = pd.read_csv("/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.tokens", delimiter="\t")
df

Warning: total number of rows (69724) exceeds max_rows (20000). Falling back to pandas display.

,paragraph_ID,sentence_ID,token_ID_within_sentence,token_ID_within_document,word,lemma,byte_onset,byte_offset,POS_tag,fine_POS_tag,dependency_relation,syntactic_head_ID,event
0,0,0,0,0,ALSO,also,3,7,ADV,RB,advmod,1,O
1,0,0,1,1,BY,by,8,10,ADP,IN,ROOT,1,O
2,0,0,2,2,CARRIE,CARRIE,11,17,PROPN,NNP,compound,4,O
3,0,0,3,3,MAC,MAC,18,21,PROPN,NNP,compound,4,O
4,1,0,4,4,Wildfire,Wildfire,26,34,PROPN,NNP,pobj,1,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69719,3222,8037,14,94456,.,.,404536,404537,PUNCT,.,punct,94442,O
69720,3223,8038,0,94457,Sign,Sign,404542,404546,PROPN,NNP,ROOT,94457,O
69721,3223,8038,1,94458,up,up,404547,404549,ADP,RP,prt,94457,O
69722,3223,8038,2,94459,now,now,404550,404553,ADV,RB,advmod,94457,O
69723,3223,8038,3,94460,.,.,404553,404554,PUNCT,.,punct,94457,O

In [ ]:
events = df[~df['event'].isnull()]
events

Warning: total number of rows (69724) exceeds max_rows (20000). Falling back to pandas display.

,paragraph_ID,sentence_ID,token_ID_within_sentence,token_ID_within_document,word,lemma,byte_onset,byte_offset,POS_tag,fine_POS_tag,dependency_relation,syntactic_head_ID,event
0,0,0,0,0,ALSO,also,3,7,ADV,RB,advmod,1,O
1,0,0,1,1,BY,by,8,10,ADP,IN,ROOT,1,O
2,0,0,2,2,CARRIE,CARRIE,11,17,PROPN,NNP,compound,4,O
3,0,0,3,3,MAC,MAC,18,21,PROPN,NNP,compound,4,O
4,1,0,4,4,Wildfire,Wildfire,26,34,PROPN,NNP,pobj,1,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69719,3222,8037,14,94456,.,.,404536,404537,PUNCT,.,punct,94442,O
69720,3223,8038,0,94457,Sign,Sign,404542,404546,PROPN,NNP,ROOT,94457,O
69721,3223,8038,1,94458,up,up,404547,404549,ADP,RP,prt,94457,O
69722,3223,8038,2,94459,now,now,404550,404553,ADV,RB,advmod,94457,O
69723,3223,8038,3,94460,.,.,404553,404554,PUNCT,.,punct,94457,O

In [ ]:
event_options = set(events.event.tolist())
print (event_options)

{'EVENT', 'O'}

In [ ]:
real_events = events.loc[df["event"] == "EVENT"]
real_events

,paragraph_ID,sentence_ID,token_ID_within_sentence,token_ID_within_document,word,lemma,byte_onset,byte_offset,POS_tag,fine_POS_tag,dependency_relation,syntactic_head_ID,event
753,107,47,5,753,took,take,4678,4682,VERB,VBD,ccomp,759,EVENT
759,107,47,11,759,threw,throw,4702,4707,VERB,VBD,ROOT,759,EVENT
781,107,48,12,781,dragged,drag,4812,4819,VERB,VBD,advcl,777,EVENT
808,107,49,5,808,researched,research,4950,4960,VERB,VBD,advcl,805,EVENT
836,107,55,1,836,read,read,5081,5085,VERB,VBD,ROOT,836,EVENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69582,3211,8021,1,94301,grab,grab,403790,403794,VERB,VBP,ROOT,94301,EVENT
69588,3211,8023,1,94312,hand,hand,403823,403827,VERB,VBP,ROOT,94312,EVENT
69595,3212,8026,1,94332,leave,leave,403892,403897,VERB,VBP,ROOT,94332,EVENT
69652,3212,8031,1,94389,smoke,smoke,404131,404136,NOUN,NN,nsubj,94390,EVENT
69656,3212,8031,5,94393,drifting,drift,404150,404158,VERB,VBG,conj,94391,EVENT

In [ ]:
event_words = set(real_events.word.tolist())
len(event_words)

1294

In [ ]:
event_lemmas = list(set(real_events.lemma.tolist()))
event_lemmas.sort()
len(event_lemmas)
print (event_lemmas[:10])

['Breathless', 'Drinking', 'Exhausted', 'Finished', 'Honking', 'Kissing', 'Rang', 'accident', 'accuse', 'ache']

In [ ]:
final_lemmas = []
for lemma in event_lemmas:
    lemma = lemma.lower()
    if lemma not in final_lemmas:
        final_lemmas.append(lemma)

print(len(final_lemmas))
print(final_lemmas[:10])

918
['breathless', 'drinking', 'exhausted', 'finished', 'honking', 'kissing', 'rang', 'accident', 'accuse', 'ache']

In [ ]:
sentences = real_events.sentence_ID.tolist()
events = real_events.word.tolist()
print (sentences[:10])
print (events[:10])

[47, 47, 48, 49, 55, 63, 64, 67, 69, 69]
['took', 'threw', 'dragged', 'researched', 'read', 'talked', 'told', 'stumped', 'took', 'admit']

In [ ]:
df

Warning: total number of rows (69724) exceeds max_rows (20000). Falling back to pandas display.

,paragraph_ID,sentence_ID,token_ID_within_sentence,token_ID_within_document,word,lemma,byte_onset,byte_offset,POS_tag,fine_POS_tag,dependency_relation,syntactic_head_ID,event
0,0,0,0,0,ALSO,also,3,7,ADV,RB,advmod,1,O
1,0,0,1,1,BY,by,8,10,ADP,IN,ROOT,1,O
2,0,0,2,2,CARRIE,CARRIE,11,17,PROPN,NNP,compound,4,O
3,0,0,3,3,MAC,MAC,18,21,PROPN,NNP,compound,4,O
4,1,0,4,4,Wildfire,Wildfire,26,34,PROPN,NNP,pobj,1,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69719,3222,8037,14,94456,.,.,404536,404537,PUNCT,.,punct,94442,O
69720,3223,8038,0,94457,Sign,Sign,404542,404546,PROPN,NNP,ROOT,94457,O
69721,3223,8038,1,94458,up,up,404547,404549,ADP,RP,prt,94457,O
69722,3223,8038,2,94459,now,now,404550,404553,ADV,RB,advmod,94457,O
69723,3223,8038,3,94460,.,.,404553,404554,PUNCT,.,punct,94457,O

In [ ]:
sentence1 = sentences[0]
result = df[df["sentence_ID"] == int(sentence1)]
result

,paragraph_ID,sentence_ID,token_ID_within_sentence,token_ID_within_document,word,lemma,byte_onset,byte_offset,POS_tag,fine_POS_tag,dependency_relation,syntactic_head_ID,event
748,107,47,0,748,But,but,4658,4661,CCONJ,CC,cc,753,O
749,107,47,1,749,the,the,4662,4665,DET,DT,det,751,O
750,107,47,2,750,last,last,4666,4670,ADJ,JJ,amod,751,O
751,107,47,3,751,time,time,4671,4675,NOUN,NN,npadvmod,753,O
752,107,47,4,752,I,I,4676,4677,PRON,PRP,nsubj,753,O
753,107,47,5,753,took,take,4678,4682,VERB,VBD,ccomp,759,EVENT
754,107,47,6,754,the,the,4683,4686,DET,DT,det,755,O
755,107,47,7,755,train,train,4687,4692,NOUN,NN,dobj,753,O
756,107,47,8,756,",",",",4692,4693,PUNCT,",",punct,759,O
757,107,47,9,757,a,a,4694,4695,DET,DT,det,758,O
758,107,47,10,758,woman,woman,4696,4701,NOUN,NN,nsubj,759,O
759,107,47,11,759,threw,throw,4702,4707,VERB,VBD,ROOT,759,EVENT
760,107,47,12,760,herself,herself,4708,4715,PRON,PRP,dobj,759,O
761,107,47,13,761,in,in,4716,4718,ADP,IN,prep,759,O
762,107,47,14,762,front,front,4719,4724,NOUN,NN,pobj,761,O
763,107,47,15,763,of,of,4725,4727,ADP,IN,prep,762,O
764,107,47,16,764,it,it,4728,4730,PRON,PRP,pobj,763,O
765,107,47,17,765,just,just,4731,4735,ADV,RB,advmod,766,O
766,107,47,18,766,outside,outside,4736,4743,ADP,IN,prep,759,O
767,107,47,19,767,Everett,Everett,4744,4751,PROPN,NNP,pobj,766,O
768,107,47,20,768,.,.,4751,4752,PUNCT,.,punct,759,O

In [ ]:
words = result.word.tolist()
resentence = " ".join(words)

In [ ]:
print (resentence)

But the last time I took the train , a woman threw herself in front of it just outside Everett .

In [ ]:
!wget "/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.tokens"

/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.tokens: Scheme missing.

In [ ]:
def grab_event_sentences(file):
    df = pd.read_csv(file, delimiter="\t")
    real_events = df.loc[df["event"] == "EVENT"]
    sentences = real_events.sentence_ID.tolist()
    event_words = real_events.word.tolist()
    event_lemmas = real_events.lemma.tolist()
    final_sentences = []
    x=0
    for sentence in sentences:
        result = df[df["sentence_ID"] == int(sentence)]
        words = result.word.tolist()
        resentence = " ".join(words)
        final_sentences.append({"event_word": event_words[x],
                                "event_lemma": event_lemmas[x],
                                "sentence": resentence
                               })
        x=x+1
    return final_sentences

In [ ]:
event_data = grab_event_sentences("/content/booknlp_sample/10 Things I Can See From Here - Carrie Mac.txt.tokens")

TypeError: ignored

In [ ]:
print (event_data[0])

In [ ]:
new_df = pd.DataFrame(event_data)
new_df

In [ ]:
new_df.to_csv("10ThingsCarrieMac.events", index=False)